### ISSUE TITLE
license of scaleworker

### ISSUE THREAD

**Issue by oliexdev** [monster1025/blegw#1]
Hi monster1025,

I am the author of [openScale](https://github.com/oliexdev/openScale/). I looked at your code [scaleworker.go](https://github.com/monster1025/blegw/blob/master/workers/scaleworker.go) and found some portions of my code in your project, which is ok, since its under GPL v3. But I couldn't find any kind of copyright notices about my code. Please note that derived work of GPL v3 code needs to be under the same licence. 
If you don't mind please include a copyright notice in your code.

Best regards
oli

**Comment by monster1025** [comment]
Hi, Oli! 

Thanks for you project and work, it's only one full implementation of scale history reading in the internet! =)
Of course, I added GPL license to my little project.
